# AI Assistant Settings
#
# Please add your OpenAI API key below.
# The AI assistant will not be able to function without it.
# You can get your key from: https://platform.openai.com/api-keys

openai_api_key: "YOUR_API_KEY_HERE"
llm_model: "gpt-4o"
