name: Monitor A
on:
  schedule: [{ cron: "30 6 * * *" }]
  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
permissions:
  contents: write
  pull-requests: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Render GAR summary
        run: poetry run python app/agents/monitor/monitor.py --emit-status

      - name: Post GAR as PR comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: poetry run python app/agents/monitor/monitor.py --emit-status --post-comments
