name: Monitor A
on:
  schedule: [{ cron: "30 6 * * *" }]
  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
permissions:
  contents: write
  pull-requests: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Render GAR summary
        run: python agents/monitor/monitor.py --emit-status
      - name: Post GAR as PR comment
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python agents/monitor/monitor.py --emit-status --post-comments
