name: Quality Gate
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - run: ruff check .
      - run: pytest agents/monitor/tests scripts/tests -q || true
