name: Quality Gate
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install ruff pytest pyyaml
      - run: ruff check .
      - run: pytest -q || true
