name: Quality Gate
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run linters and formatters
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run isort --check-only .
      
      - name: Run tests
        run: poetry run pytest -q
